### PR TITLE
Allow overriding DOCKER_HUB_REPO

### LINKED ISSUE #7: How to switch repo?
I am following the tutorial in `http://www.bugswarm.org/docs/tutorials/setting-up-an-experiment/`.

When running an artifact with `bugswarm run --image-tag nutzam-nutz-140438299 --use-sandbox`, the repo `bugswarm/images` is used (which is set in `.../site-packages/bugswarm/common/credentials.py`), but how can I switch to another repo (say https://hub.docker.com/repository/docker/lxylxy123456/bugswarm-repo)? 

Is there a standard procedure for editing `credentials.py`? Or maybe we can add a command line argument.

### PR DESCRIPTION
**Pull request by lxylxy123456**
Allow the user to change `DOCKER_HUB_REPO` by `--docker-hub-repo` instead of modifying something like `~/.local/lib/python3.?/site-packages/bugswarm/common/credentials.py`
Close #7

### CODE REVIEW

**Review by dtomassi — COMMENTED** [review]
Interesting change. Is this something we want?

If so, we would then probably have to support the change of having it look at a different (local) database with the `show` command.

**Comment by lxylxy123456** [comment]
I think we need it when we need to use an experimental repo or the cached repo (bugswarm/cached-images). Currently the only workaround I know is #7, but I hope this can be a better way.

**Comment by dtomassi** [comment]
> I think we need it when we need to use an experimental repo or the cached repo (bugswarm/cached-images). Currently the only workaround I know is #7, but I hope this can be a better way.

What do you mean an experimental repo?

If you are doing some testing, you do not have to use the client. You can use Docker commands.

**Comment by lxylxy123456** [comment]
> > I think we need it when we need to use an experimental repo or the cached repo (bugswarm/cached-images). Currently the only workaround I know is #7, but I hope this can be a better way.
> 
> What do you mean an experimental repo?

Something like https://hub.docker.com/repository/docker/lxylxy123456/bugswarm-repo , which was created when I was running the bugswarm pipeline.

> 
> If you are doing some testing, you do not have to use the client. You can use Docker commands.

Just to clarify, are the following two commands equivalent?
```
$ bugswarm run --image-tag apache-commons-lang-159112598 --docker-hub-repo bugswarm/cached-images
$ docker run --rm -it bugswarm/cached-images:apache-commons-lang-159112598 
```

**Comment by dtomassi** [comment]
> > > I think we need it when we need to use an experimental repo or the cached repo (bugswarm/cached-images). Currently the only workaround I know is #7, but I hope this can be a better way.
> > 
> > 
> > What do you mean an experimental repo?
> 
> Something like https://hub.docker.com/repository/docker/lxylxy123456/bugswarm-repo , which was created when I was running the bugswarm pipeline.
> 
> > If you are doing some testing, you do not have to use the client. You can use Docker commands.
> 
> Just to clarify, are the following two commands equivalent?
> 
> ```
> $ bugswarm run --image-tag apache-commons-lang-159112598 --docker-hub-repo bugswarm/cached-images
> $ docker run --rm -it bugswarm/cached-images:apache-commons-lang-159112598 
> ```

Yes those commands should be equivalent.

**Comment by lxylxy123456** [comment]
Closing this issue because there is a workaround.

**Pull request closed without merging**
